# Generated by Django 2.2.16 on 2021-12-02 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category-name')),
                ('slug', models.SlugField(unique=True, verbose_name='category-slug')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='genre-name')),
                ('slug', models.SlugField(unique=True, verbose_name='genre-slug')),
            ],
        ),
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.Genre', verbose_name='genre')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='title-name')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2021, message='Вы пытаетесь внести еще не вышедшее произведение')], verbose_name='title-year')),
                ('description', models.TextField(blank=True, verbose_name='title-description')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', to='artworks.Category', verbose_name='title-category')),
                ('genre', models.ManyToManyField(through='artworks.GenreTitle', to='artworks.Genre', verbose_name='title-genre')),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.AddField(
            model_name='genretitle',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.Title', verbose_name='genre-title'),
        ),
    ]
